name: flux-core
version: 0.1.0.0
dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Flux.Types.Payment
    - Flux.Types.Workflow
    - Flux.Types.Error
    - Flux.Engine.Interpreter
    - Flux.Engine.Validator
    - Flux.DSL.Parser
    - Flux.DSL.Compiler

executables:
  flux:
    main: Main.hs
    source-dirs: src
